rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"

zipkin:
  image: openzipkin/zipkin
  ports:
    - "9411:9411"

eureka-server:
  build:  eureka-server/
  hostname: eureka-server
  ports:
    - "8761:8761"

config-server:
  build: config-server/
  links:
    - "eureka-server"
    - "rabbitmq"
  volumes:
    - ./config-server/config:/app/config

zuul:
  build: zuul/
  ports:
    - "8765:8765"
  links:
    - "eureka-server"
    - "config-server"
    - "account-service"
    - "customer-service"
    - "rabbitmq"
    - "zipkin"

account-service:
  build: account-service/
  links:
    - "eureka-server"
    - "config-server"
    # - "hystrix-dashboard"
    - "rabbitmq"
    - "zipkin"

customer-service:
  build: customer-service/
  links:
    - "eureka-server"
    - "config-server"
    - "account-service"
    # - "hystrix-dashboard"
    - "rabbitmq"
    - "zipkin"
    
# admin-dashboard:
#   build: admin-dashboard/
#   ports:
#     - "8040:8040"
  # links:
  #   - "eureka-server"
  #   - "rabbitmq"
  #   - "config-server"
  #   - "service-a"
  #   - "service-b"
  #   - "zuul"
  #   - "hystrix-dashboard"



# hystrix-dashboard:
#   build:  hystrix-dashboard/
#   ports:
#     - "8050:8050"
#   links:
#     - "eureka-server"




    